### PR TITLE
📝 Use the *Consortium for Python Data API Standards* Code of Conduct

### PR DESCRIPTION
**Pull request by jorenham**

### CODE REVIEW

**Comment by jorenham** [comment]
hmm I was going for italic actually 🤔

**Review by nstarman — APPROVED** [review]

**Comment by nstarman** [comment]
@jorenham, what's the min version of the API we want to support?

**Comment by jorenham** [comment]
> @jorenham, what's the min version of the API we want to support?

We could try starting with 2021

**Comment by nstarman** [comment]
Great. Created and set a milestone for `YYYY-MM-minor.bugfix`

**Pull request merged**
