### PR TITLE
💄 Add a `black`-compatible `.editorconfig`

### PR DESCRIPTION
**Pull request by jorenham**
https://editorconfig.org/

### CODE REVIEW

**Review by nstarman — COMMENTED** [review]
Is there a way to set configurations, e.g. `max_line_length = 88` from `pyproject.toml` ? It would be best to have a single source of truth?

**Comment by jorenham** [comment]
> Is there a way to set configurations, e.g. `max_line_length = 88` from `pyproject.toml` ? It would be best to have a single source of truth.

`ruff` uses these settings by default 🤷🏻

**Comment by jorenham** [comment]
> Is there a way to set configurations, e.g. `max_line_length = 88` from `pyproject.toml` ? It would be best to have a single source of truth.

and to answer your question; no, I don't think the editorconfig spec supports dynamic settings

**Comment by nstarman** [comment]
Nor the reverse, unfortunately: https://github.com/astral-sh/ruff/issues/1530

**Comment by nstarman** [comment]
That being said, if we treat `.editorconfig` as the SSoT and have comments on all related configs warning that the two should be kept in sync, then it's fine 🤞 .

**Comment by nstarman** [comment]
OTOH. Doesn't pre-commit fix most of these?

**Comment by jorenham** [comment]
I wasn't aware that pre-commit looked at this?

**Comment by nstarman** [comment]
not this file specifically, but hooks can fix line endings, tab-size, etc.

**Comment by jorenham** [comment]
Oh btw, the `max_line_length = 88` is in the editorconfig spec, but I've seen it used in several other places (such as numpy) 🤷🏻

**Comment by jorenham** [comment]
> not this config file specifically, but hooks can fix line endings, tab-size, etc.

Yea, there's hooks for most of these. This config is mostly useful for IDE's

**Comment by nstarman** [comment]
hmm.. I get why it's useful. I just have the same concern as https://github.com/astral-sh/ruff/issues/1530#issuecomment-1546176355

**Comment by jorenham** [comment]
> hmm.. I get why it's useful. I just have the same concern as [astral-sh/ruff#1530 (comment)](https://github.com/astral-sh/ruff/issues/1530#issuecomment-1546176355)

Yea I can see that; I prefer a minimal amount of files in the root myself as well.
But in practice, this is one of those configs that you shouldn't have to touch ever again. And if I remember correctly, `repo-review` also requires this.

**Comment by jorenham** [comment]
But I'm also fine with not having an editorconfig; I can configure vscode myself just fine 🤷🏻

**Comment by nstarman** [comment]
With [git-exclude](https://git-scm.com/docs/gitignore#_configuration) you can have it and the ignore won't be forced on others...

**Comment by nstarman** [comment]
But with good code comments in `pyproject.toml` and in `editorconfig`, I'm also fine to merge this.

**Comment by jorenham** [comment]
> With [git-exclude](https://git-scm.com/docs/gitignore#_configuration) you can have it and the ignore won't be forced on others...

Yea, I use that for a bunch of cache dirs. But I don't think I even use editorconfig; I only added it because others might use it.

**Comment by jorenham** [comment]
Let's close this then; we could always reconsider later if someone asks for it

**Pull request closed without merging**
